# Generated by Django 5.1.2 on 2024-11-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_titile',
            new_name='offer_title',
        ),
    ]
