# Generated by Django 5.1.2 on 2024-11-02 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_coupen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=255)),
                ('banner_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banner_image', models.ImageField(upload_to='banner/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_listed', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
