# Generated by Django 5.1.2 on 2024-11-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="deal_price",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="is_listed",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="price",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="product",
        ),
    ]
