# Generated by Django 5.1.2 on 2024-11-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_remove_banner_deal_price_remove_banner_is_listed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
