# Generated by Django 5.1.2 on 2024-11-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
        ("product", "0010_product_sold_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offer.offer",
            ),
        ),
        migrations.DeleteModel(
            name="Offer",
        ),
    ]
