# Generated by Django 5.1.2 on 2024-11-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="offer",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
