# Generated by Django 5.1.2 on 2024-11-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_rename_category_image_sub_category_category"),
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sub_category",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offer.offer",
            ),
        ),
    ]
