# Generated by Django 5.1.2 on 2024-11-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_item_varient"),
        ("product", "0007_productreview"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart_item",
            unique_together={("cart", "product", "varient")},
        ),
    ]
