# Generated by Django 5.1.2 on 2026-04-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_item_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=100)),
                (
                    "book_name",
                    models.ManyToManyField(related_name="book", to="cart.book"),
                ),
            ],
        ),
    ]
