# Generated by Django 5.1.2 on 2024-11-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0010_product_sold_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.coupen",
            ),
        ),
    ]
