# Generated by Django 5.1.2 on 2024-11-15 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_payment_payment_status"),
        ("product", "0010_product_sold_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="varient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.varient",
            ),
        ),
    ]
