# Generated by Django 5.1.2 on 2024-11-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_orderitems_varient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitems",
            name="return_reason",
        ),
        migrations.AddField(
            model_name="orderitems",
            name="item_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
