# Generated by Django 5.1.2 on 2024-11-20 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_remove_orderitems_return_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("landmark", models.CharField(blank=True, max_length=255, null=True)),
                ("postal_code", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                (
                    "alternative_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderaddress",
                        to="order.order",
                    ),
                ),
            ],
        ),
    ]
