# Generated by Django 5.1.2 on 2024-11-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_orderaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
