# Generated by Django 5.1.2 on 2024-11-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_remove_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                    ("payment_pending", "Payment Pending"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
