# Generated by Django 5.1.2 on 2024-11-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
