# Generated by Django 5.1.2 on 2024-11-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_payment_payment_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
