# Generated by Django 5.1.2 on 2026-02-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_orderitems_return_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransation",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("refund", "Refund"),
                    ("cancellation", "Cancellation"),
                    ("debited", "Debited"),
                    ("referral", "Referral Bonus"),
                ],
                max_length=20,
            ),
        ),
    ]
