# Generated by Django 5.1.2 on 2026-04-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_alter_wallettransation_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitems",
            name="return_reason",
        ),
        migrations.AddField(
            model_name="orderitems",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="cancel_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
