# Generated by Django 5.1.2 on 2026-04-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_remove_orderitems_return_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitems",
            name="cancel_reason",
        ),
    ]
