# Generated by Django 5.1.2 on 2026-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_remove_orderitems_cancel_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="return_status",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
